### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by PaulDreef** [lbke/awesome-vulcan#1]
Hi Ibke,

Very nice work, I love Vulcan, and metials design, so I tought.. this is an amazing setup.. But I get an error on build:

/home/paul/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20181021-23:06:12.972(2)? (STDERR) 						throw(ex);
W20181021-23:06:12.972(2)? (STDERR) 						^
W20181021-23:06:12.972(2)? (STDERR) 
W20181021-23:06:12.973(2)? (STDERR) TypeError: Cannot read property 'func' of undefined
W20181021-23:06:12.973(2)? (STDERR)     at Button.jsx (packages/vulcan:accounts/imports/ui/components/Button.jsx:31:28)
W20181021-23:06:12.973(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181021-23:06:12.974(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181021-23:06:12.975(2)? (STDERR)     at Module.moduleLink [as link] (/home/paul/.meteor/packages/modules/.0.13.0.v7rrc0.mq6ad++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20181021-23:06:12.979(2)? (STDERR)     at components.js (packages/vulcan:accounts/imports/components.js:1:8)
W20181021-23:06:12.980(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181021-23:06:12.982(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181021-23:06:12.983(2)? (STDERR)     at Module.moduleLink [as link] (/home/paul/.meteor/packages/modules/.0.13.0.v7rrc0.mq6ad++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20181021-23:06:12.984(2)? (STDERR)     at main_server.js (packages/vulcan:accounts/main_server.js:1:204)
W20181021-23:06:12.984(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181021-23:06:12.985(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181021-23:06:12.986(2)? (STDERR)     at require (packages/modules-runtime.js:258:21)

I installed the additional packages in a seperate folder an created an meteor_package_dir variable in my Bash.

Do you know what I'm doing wrong ?

npm update etc.. wont work either..

Grtz,

Paul

**Comment by eric-burel** [comment]
Hi Paul, thanks for the feedback! I am working on an app based on this code right now so don't hesitate to open issues in the days to come, I will try to fix them asap. I will improve the Readme too to help installation.

Right now your issue is that `prop-types` is not installed, it's in the package.json though. Try running `meteor npm install` again and let me know.

**Comment by eric-burel** [comment]
Hi Paul,
Sorry if you have my answer twice, I have trouble interacting with github today. Thanks for the positive feedback!
It sounds like `prop-types` is not installed. 2-repo install are sadly subject to issues regarding npm packages. Try installing or reinstalling `prop-types` (and other npm packages that could lead to issues) in both your Awesome Vulcan package AND your Vulcan folder (note that I use the latest commits on devel). Here it may be related to https://github.com/lbke/vulcan-users-manager/blob/master/package.js.

I will improve the Readme asap.

**Comment by PaulDreef** [comment]
Hi Eric,

Tried, sorry, no succes:

W20181022-09:57:11.434(2)? (STDERR) /home/paul/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20181022-09:57:11.435(2)? (STDERR) 						throw(ex);
W20181022-09:57:11.435(2)? (STDERR) 						^
W20181022-09:57:11.435(2)? (STDERR) 
W20181022-09:57:11.435(2)? (STDERR) TypeError: Cannot read property 'func' of undefined
W20181022-09:57:11.435(2)? (STDERR)     at Button.jsx (packages/vulcan:accounts/imports/ui/components/Button.jsx:31:28)
W20181022-09:57:11.436(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181022-09:57:11.436(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181022-09:57:11.436(2)? (STDERR)     at Module.moduleLink [as link] (/home/paul/.meteor/packages/modules/.0.13.0.v7rrc0.mq6ad++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20181022-09:57:11.436(2)? (STDERR)     at components.js (packages/vulcan:accounts/imports/components.js:1:8)
W20181022-09:57:11.437(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181022-09:57:11.437(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181022-09:57:11.437(2)? (STDERR)     at Module.moduleLink [as link] (/home/paul/.meteor/packages/modules/.0.13.0.v7rrc0.mq6ad++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20181022-09:57:11.437(2)? (STDERR)     at main_server.js (packages/vulcan:accounts/main_server.js:1:204)
W20181022-09:57:11.438(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181022-09:57:11.438(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181022-09:57:11.438(2)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20181022-09:57:11.438(2)? (STDERR)     at /home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/packages/vulcan_accounts.js:2376:15
W20181022-09:57:11.438(2)? (STDERR)     at /home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/packages/vulcan_accounts.js:2381:3
W20181022-09:57:11.438(2)? (STDERR)     at /home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/boot.js:411:36
W20181022-09:57:11.439(2)? (STDERR)     at Array.forEach (<anonymous>)
W20181022-09:57:11.439(2)? (STDERR)     at /home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/boot.js:220:19
W20181022-09:57:11.439(2)? (STDERR)     at /home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/boot.js:471:5
W20181022-09:57:11.439(2)? (STDERR)     at Function.run (/home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/profile.js:510:12)
W20181022-09:57:11.439(2)? (STDERR)     at /home/paul/Vulcan-awesome/awesome-vulcan/.meteor/local/build/programs/server/boot.js:470:11

I also get these warnings after a npm install:

npm WARN apollo-link@1.2.3 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-16@1.6.0 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN formsy-react@0.19.5 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datetime@2.16.1 requires a peer of moment-timezone@^0.5.13 but none is installed. You must install peer dependencies yourself.

Is that something I have to worry about ?

Grtz,

Paul

**Comment by PaulDreef** [comment]
Tried also the prop-types install, no luck...

**Comment by eric-burel** [comment]
I've pushed a bunch of updates this morning and tried to write a doc to make install easier, let me know. You might need to run an npm install in all the packages too (not sure yet though).

**Comment by ghost** [comment]
Hi Eric,

Tried to find you on slack, can you add me ? phj.dreef@gmail.com..
bcrypt was a pain.. but I ran: 
npm install --save bcrypt-nodejs && npm uninstall --save bcrypt

npm start give still the error on vulcan:accounts/.../Button.jsx (Cannot read property 'func' of undefined)

Whick version of accounts do you use ? (vulcan:accounts                added, version 1.3.2)

Grtz,

Paul

**Comment by eric-burel** [comment]
Hi, sorry I did not get your last message sooner, did you get rid of this / access the Slack?
